version: '3.8'
services:
  fastapi:
    build:
      context: ..
      dockerfile: src/Dockerfile
    depends_on:
      - postgres
      - redis
      - mongo
    ports:
      - "8000:8000"
    networks:
      - my_network

  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  redis:
    image: redis:latest
    command: redis-server --requirepass redis!123
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - my_network

  mongo:
     image: mongo:latest
     ports:
       - "27017:27017"
     volumes:
       - mongo_data:/data
     environment:
       - MONGO_INITDB_ROOT_USERNAME=root
       - MONGO_INITDB_ROOT_PASSWORD=root

volumes:
  postgres_data:
  redis_data:
networks:
  my_network: